### ISSUE TITLE
Duplicated Link

### ISSUE THREAD

**Issue by Nifalu** [unibas-marcelluethi/software-engineering#72]
In [Week5](https://unibas-marcelluethi.github.io/software-engineering/week5/) bei **Vorbereitung Schritt 5b** ist ein falscher Link. Anstatt ein Blog Eintrag von Dan North ist nochmals der Link zu den Slides von **Schritt 5a** hinterlegt.

**Comment by marcelluethi** [comment]
Vielen Dank für den Hinweis. Ich habe den Link gerade korrigiert.
